### RestClient VScode extension to quickly goto links to test my http requests
### (frontend has to fetch these)


### GET (ALL)
GET http://localhost:3001/api/listing

### GET (ALL) (THAT MATCH THE SPECIFIED NAME REGEX)
GET http://localhost:3001/api/listing
Content-Type: application/json

{
    "name": "cat"
}


### GET (ONE) :ID
GET http://localhost:3001/api/listing/69dd33f2adc298b203a081f0
###

### CREATE (a new object with specified data (data is JSON))
# MUST BE SPACE BETWEEN HTTP REQUEST AND JSON BODY (req.body), also must tell it to read json
POST http://localhost:3001/api/listing
Content-Type: application/json

{
    "name": "Cat-Nip",
    "sellerName": "John Arbuckle",
    "price": "20.00"
}

### DELETE (ONE) :ID
DELETE http://localhost:3001/api/listing/69dd33dcadc298b203a081ef

### DELETE ALL
DELETE http://localhost:3001/api/listing

### UPDATE(PATCH) (ONE) needs req.body so it uses json to get the updated info to send to the server
### patch means update these properties, keep the rest as is. Put means remove all the props' values and replace with these
PATCH http://localhost:3001/api/listing/69dabf3a36df2232b1a2551f
Content-Type: application/json

{
    "name": "updatedpibby",
    "subscribedToChannel": ["pim", "cheese", "raddishgaming"]
}